name: Build plugins
on:
  pull_request:
  push:
jobs:
  # linux:
  #   strategy:
  #     matrix:
  #       target:
  #         [linux-arm64, linux-x86_64]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         submodules: recursive
  #     - uses: distrho/dpf-cmake-action@v1
  #       with:
  #         target: ${{ matrix.target }}

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: distrho/dpf-cmake-action@v1
        with:
          target: macos-universal
          lto: true

  windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ucrt64
          update: true
          pacboy: >-
            toolchain:p
            cmake:p
            ninja:p
            glew:p
      - name: Build plugin
        run: |
          cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
          cmake --build build
      - name: Create release package
        working-directory: build
        run: |
          cpack -G NSIS
          cpack -G ZIP
      - uses: actions/upload-artifact@v3
        with:
          name: Misstrhortion-${{ github.sha }}-win64.exe
          path: build/Misstrhortion-*-win64.exe
      - uses: actions/upload-artifact@v3
        with:
          name: Misstrhortion-${{ github.sha }}-win64.zip
          path: build/Misstrhortion-*-win64.zip
