name: Build plugins
on:
  pull_request:
  push:
jobs:
  # linux:
  #   strategy:
  #     matrix:
  #       target:
  #         [linux-arm64, linux-x86_64]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         submodules: recursive
  #     - uses: distrho/dpf-cmake-action@v1
  #       with:
  #         target: ${{ matrix.target }}

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: distrho/dpf-cmake-action@v1
        with:
          target: macos-universal
          lto: true

  windows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: distrho/dpf-cmake-action@v1
        with:
          target: win64
          pawpaw: true

  source:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: distrho/dpf-makefile-action@v1
        with:
          target: source
